name: Pulumi AWS Infra Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy AWS Infra with Pulumi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Setup Pulumi CLI
        uses: pulumi/actions@v5
        with:
          pulumi-version: '3.120.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Pulumi Cloud
        run: pulumi login

      - name: Preview Deployment
        run: pulumi preview

      - name: Deploy Resources
        run: pulumi up --yes
